package DB;
// Generated 26/11/2013 11:14:23 by Hibernate Tools 3.2.1.GA



/**
 * Assunto generated by hbm2java
 */
public class Assunto  implements java.io.Serializable {


     private int idassunto;
     private String assunto;

    public Assunto() {
    }

    public Assunto(int idassunto, String assunto) {
       this.idassunto = idassunto;
       this.assunto = assunto;
    }
   
    public int getIdassunto() {
        return this.idassunto;
    }
    
    public void setIdassunto(int idassunto) {
        this.idassunto = idassunto;
    }
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }




}


