package DB;
// Generated 26/11/2013 11:14:23 by Hibernate Tools 3.2.1.GA



/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int idlocal;
     private String local;

    public Local() {
    }

    public Local(int idlocal, String local) {
       this.idlocal = idlocal;
       this.local = local;
    }
   
    public int getIdlocal() {
        return this.idlocal;
    }
    
    public void setIdlocal(int idlocal) {
        this.idlocal = idlocal;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }




}


