package DB;
// Generated 26/11/2013 11:14:23 by Hibernate Tools 3.2.1.GA



/**
 * Procurador generated by hbm2java
 */
public class Procurador  implements java.io.Serializable {


     private int idprocurador;  
     private String nome;
     private String sigla;
     private Integer antiguidade;
     private String area;
     private Integer ultimo;
     private int atuando;

    public Procurador() {
    }

	
    public Procurador(int idprocurador, String nome, String sigla, Integer antiguidade, String area, Integer ultimo, int atuando) {
        this.idprocurador = idprocurador;
        this.nome = nome;
        this.sigla = sigla;
        this.antiguidade = antiguidade;
        this.area = area;
        this.ultimo = ultimo;
        this.atuando = atuando;
    }
    
    public Procurador(int idprocurador, String nome, String sigla, Integer antiguidade, String area) {
       this.idprocurador = idprocurador;
       this.nome = nome;
       this.sigla = sigla;
       this.antiguidade = antiguidade;
       this.area = area;
    }
   
    public int getIdProcurador() {
        return this.idprocurador;
    }
    
    public int getIdprocurador() {
        return this.idprocurador;
    }
    
    public void setIdProcurador(int idprocurador) {
        this.idprocurador = idprocurador;
    }
    
    public void setIdprocurador(int idprocurador) {
        this.idprocurador = idprocurador;
    }
    
    public String getNome() {
        return this.nome;
    }
    
    public String getProcurador() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    public void setProcurador(String nome) {
        this.nome = nome;
    }
    
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    
    public Integer getAntiguidade() {
        return this.antiguidade;
    }
    
    public void setAntiguidade(Integer antiguidade) {
        this.antiguidade = antiguidade;
    }
    
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    public Integer getUltimo() {
        return this.ultimo;
    }

    public void setUltimo(Integer ultimo) {
        this.ultimo = ultimo;
    }
    
    public int getAtuando() {
        return this.atuando;
    }
    
    public void setAtuando(int atuando) {
        this.atuando = atuando;
    }

}


